services:
  #Database
  rcanyon_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3325:3306
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: rcanyon_db
  #Web
  rcanyon_wp:
    depends_on:
      - rcanyon_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8089:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: rcanyon_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    container_name: rcanyon_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  rcanyon_myadmin:
    image: phpmyadmin:latest
    container_name: rcanyon_myadmin
    restart: "no"
    ports:
      - 5009:80
    environment:
      PMA_HOST: rcanyon_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - rcanyon_db
volumes:
  db_data:
  wp-content:
